### ISSUE TITLE
After boot always showing disconnected status

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/wingpanel-indicator-network#47]
Hi.
After the last update to v.2.1.0, for the first time ever I have a small issue. After every boot indicator is showing disconnected status while Wi-Fi is working just fine. I need to disable or disconnect and reconnect so that indicator would pick up the right status.
Screenshot: https://imgur.com/wjkIgDI

**Comment by truscellino** [comment]
exactly the same for me on 2 different machines, since updates on 14th September...

**Comment by ultraviolet-1986** [comment]
I can also confirm this after updating today. Funnily enough, the login screen shows that I am connected but it shows disconnected on login each time.

I have also tried restarting the networking service through systemd and restarting but it just shows the same status on login as above.

**Comment by ultraviolet-1986** [comment]
Hi, I see this as closed - however it is still happening for me. I have reset my network connections, cleared all settings and added them again but the indicator still shows 'disconnected' even though I am connected.

As before, this happens after logging in every time but the login screen shows this indicator as connected.

Note: I am using WiFi and have also restarted the machine hot and cold.

**Comment by ultraviolet-1986** [comment]
Rather than place another update to the above, I thought I would just add another comment. Although the issue appears to be fixed, I am experiencing this issue intermittently - sometimes the icon will not show my WiFi connected for several minutes at a time, show it immediately, or not at all. Once again, my machine is fully up-to-date at the time of writing.

Apologies for keeping this one alive, I could always open a new issue but I'd rather keep all this in one place for everyone's sake. Thank you.

**Comment by danrabbit** [comment]
@ultraviolet-1986 This issue should be fixed in git master, but an update containing the fix has not been released. If you'd like to test the fix, you'll need to compile this repo from git

**Comment by ultraviolet-1986** [comment]
Hi again, sorry to take so long to reply - this is working absolutely perfect now. I took a little time to clean my system and reinstall elementary this morning and it works perfectly on this install too. ^_^b

Thank you!
