### ISSUE TITLE
GSM modem not available in switchboard and wingpanel

### ISSUE THREAD

**Issue by gwojcieszczuk** [elementary/wingpanel-indicator-network#72]
**Environment Details:**

OS: elementary OS 0.4.1 Loki
I'm using GSM LTE modem (mini-pci card) Sierra Wireless MC7304.
Kernel: 4.4.0-116-generic

**Problem description:**

Option to switch network connection to LTE modem not available in switchboard and wingpanel.
Option for "Mobile Broadband"  is available when using nm-connection-editor. I'm able to establish mobile broadband connection by interacting directly with network manager (nmcli).

**Question:**

Are you planning to include Mobile broadband icons in switchboard and wingpanel?

**Comment by davidmhewitt** [comment]
Hey, thank you for the issue report.

Mobile broadband devices are already supported by the currently unreleased versions of the network plugins for switchboard and wingpanel.

These new versions are due to be released with the new Juno version of elementary. I'll close this issue as we're just awaiting a new version of the two plugins to be released and I don't believe there's any extra work we need to do to support these devices.

Let us know if you have any issues with mobile broadband support once these are released.

Thank you,
David
